# Powered by Application Builder: https://github.com/golift/application-builder
jobs:
  include:
  - os: osx
    osx_image: xcode12
    language: go
    go: 1.16.x
  - os: linux
    dist: bionic
    services: docker
    language: go
    go: 1.16.x
git:
  depth: false
addons:
  homebrew:
    packages:
    - upx
  apt:
    packages:
    - ruby-dev
    - rpm
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - zip
    - debsigs
    - gnupg
    - upx
install:
  - mkdir -p $(go env GOPATH)/bin
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.40.1
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then rvm install 2.6.0; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then rvm 2.6.0 do gem install --no-document fpm; fi
before_script:
  # Create your own deploy key, tar it, and encrypt the file to make this work. Optionally add a bitly_token file to the archive.
  - openssl aes-256-cbc -K $encrypted_772fc4772f04_key -iv $encrypted_772fc4772f04_iv -in .secret_files.tar.enc -out .secret_files.tar -d
  - tar -xf .secret_files.tar
  - gpg --import gpg.signing.key
  - rm -f gpg.signing.key .secret_files.tar
  - source settings.sh
script:
  # Test Go.
  - make test
  # Test Docker.
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make docker; fi
  # Test built docker image.
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker run $BINARY -v 2>&1 | grep -Eq "^$BINARY,? v.*$VERSION"; fi
  # Build everything
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then rvm 2.6.0 do make release; fi
  # Build mac binary or image.
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then make dmg; fi
  # Test homebrew (with make install).
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then make install VERSION=$VERSION ITERATION=$ITERATION PREFIX=/tmp/ab-$VERSION ETC=/tmp/ab-$VERSION/etc; fi
after_success:
  # Display Release Folder
  - ls -l release/
  # Setup the ssh client so we can clone and push to the homebrew formula repo.
  # You must put github_deploy_file into .secret_files.tar.enc
  # This is an ssh key added to your homebrew forumla repo.
  - |
    mkdir -p $HOME/.ssh
    declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
    echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> $HOME/.ssh/config
    [ ! -f github_deploy_key ] || (mv github_deploy_key $SSH_FILE \
      && chmod 600 "$SSH_FILE" \
      && printf "%s\n" \
        "Host github.com" \
        "  IdentityFile $SSH_FILE" \
        "  StrictHostKeyChecking no" \
        "  LogLevel ERROR" >> $HOME/.ssh/config)
deploy:
  # Unstable (master pushes).
  - provider: packagecloud
    repository: unstable
    username: golift
    token:
      secure: PuwkeI7VlBBEpg9b6KsQy4lDEt10dQuDsZ1qVQBEllqUmpfRbn2EGk8b7nTiRTjfCVT9u1FX4I43MN/IBdgJPg9fI3YQcg5/lbEUrqDLtgo/MsP8pvMnXuhU+JuROdOHJP7/mVJrOOjDJBykTkHgtHhUcd7DcgNL5wytVdxU9szbeSns1MDK6ZPN2zxGYj9H7hmGGPWXSyNFwl87fL9629KEXUh7Ad85/G/EACdv1USz3ZHjOVt7KaUuaK/tnlyygH1WH5ynV5CRuVgcIivGPjsLqbPYGv1OUbg2bq6JcLBgXivmiN+CI6C0LjlZEgYxaEw0ynyCbBTGkRRWSez5LiMsGHfPQynrw7MA6ZCkzfdVHCPT4HSdTCTc6g4kLvf7q2HRVeED07e8RFaNWrxJyOCE05L5PhKHpTilkJjrFVV19hluM95L1xnNEGWRpkJxjrFqwf7l2Y425+pTYwa2wrLdtULkGyLA2Wf7EHqGY2f9LZ3g32In1/do34MCDO/STUBpwIR+PqvATmqbVM8/otq1wmJD5yGmb0U9dp1CPZ3jdKjzlVJ8x7FLVwXhIKZJIh7RdOm7zsfmWvRvQkx0MyFtA4eoekYig+AmJEA+fCCqBQgdB1FHKRoElDUCRw3nyhhYamt6rDdqPxVPVHi87iRdg+OcUEtPNFrUxZDaJHU=
    dist: ubuntu/focal
    local-dir: release
    package_glob: "*.deb"
    skip_cleanup: true
    cleanup: false
    on:
      branch: unstable
      condition: "$TRAVIS_OS_NAME = linux"
  - provider: packagecloud
    repository: unstable
    username: golift
    token:
      secure: PuwkeI7VlBBEpg9b6KsQy4lDEt10dQuDsZ1qVQBEllqUmpfRbn2EGk8b7nTiRTjfCVT9u1FX4I43MN/IBdgJPg9fI3YQcg5/lbEUrqDLtgo/MsP8pvMnXuhU+JuROdOHJP7/mVJrOOjDJBykTkHgtHhUcd7DcgNL5wytVdxU9szbeSns1MDK6ZPN2zxGYj9H7hmGGPWXSyNFwl87fL9629KEXUh7Ad85/G/EACdv1USz3ZHjOVt7KaUuaK/tnlyygH1WH5ynV5CRuVgcIivGPjsLqbPYGv1OUbg2bq6JcLBgXivmiN+CI6C0LjlZEgYxaEw0ynyCbBTGkRRWSez5LiMsGHfPQynrw7MA6ZCkzfdVHCPT4HSdTCTc6g4kLvf7q2HRVeED07e8RFaNWrxJyOCE05L5PhKHpTilkJjrFVV19hluM95L1xnNEGWRpkJxjrFqwf7l2Y425+pTYwa2wrLdtULkGyLA2Wf7EHqGY2f9LZ3g32In1/do34MCDO/STUBpwIR+PqvATmqbVM8/otq1wmJD5yGmb0U9dp1CPZ3jdKjzlVJ8x7FLVwXhIKZJIh7RdOm7zsfmWvRvQkx0MyFtA4eoekYig+AmJEA+fCCqBQgdB1FHKRoElDUCRw3nyhhYamt6rDdqPxVPVHi87iRdg+OcUEtPNFrUxZDaJHU=
    dist: el/6
    local-dir: release
    package_glob: "*.rpm"
    skip_cleanup: true
    cleanup: false
    on:
      branch: unstable
      condition: "$TRAVIS_OS_NAME = linux"
  # Stable packages (releases).
  - provider: packagecloud
    repository: pkgs
    username: golift
    token:
      secure: PuwkeI7VlBBEpg9b6KsQy4lDEt10dQuDsZ1qVQBEllqUmpfRbn2EGk8b7nTiRTjfCVT9u1FX4I43MN/IBdgJPg9fI3YQcg5/lbEUrqDLtgo/MsP8pvMnXuhU+JuROdOHJP7/mVJrOOjDJBykTkHgtHhUcd7DcgNL5wytVdxU9szbeSns1MDK6ZPN2zxGYj9H7hmGGPWXSyNFwl87fL9629KEXUh7Ad85/G/EACdv1USz3ZHjOVt7KaUuaK/tnlyygH1WH5ynV5CRuVgcIivGPjsLqbPYGv1OUbg2bq6JcLBgXivmiN+CI6C0LjlZEgYxaEw0ynyCbBTGkRRWSez5LiMsGHfPQynrw7MA6ZCkzfdVHCPT4HSdTCTc6g4kLvf7q2HRVeED07e8RFaNWrxJyOCE05L5PhKHpTilkJjrFVV19hluM95L1xnNEGWRpkJxjrFqwf7l2Y425+pTYwa2wrLdtULkGyLA2Wf7EHqGY2f9LZ3g32In1/do34MCDO/STUBpwIR+PqvATmqbVM8/otq1wmJD5yGmb0U9dp1CPZ3jdKjzlVJ8x7FLVwXhIKZJIh7RdOm7zsfmWvRvQkx0MyFtA4eoekYig+AmJEA+fCCqBQgdB1FHKRoElDUCRw3nyhhYamt6rDdqPxVPVHi87iRdg+OcUEtPNFrUxZDaJHU=
    dist: ubuntu/focal
    local-dir: release
    package_glob: "*.deb"
    skip_cleanup: true
    cleanup: false
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
  - provider: packagecloud
    repository: pkgs
    username: golift
    token:
      secure: PuwkeI7VlBBEpg9b6KsQy4lDEt10dQuDsZ1qVQBEllqUmpfRbn2EGk8b7nTiRTjfCVT9u1FX4I43MN/IBdgJPg9fI3YQcg5/lbEUrqDLtgo/MsP8pvMnXuhU+JuROdOHJP7/mVJrOOjDJBykTkHgtHhUcd7DcgNL5wytVdxU9szbeSns1MDK6ZPN2zxGYj9H7hmGGPWXSyNFwl87fL9629KEXUh7Ad85/G/EACdv1USz3ZHjOVt7KaUuaK/tnlyygH1WH5ynV5CRuVgcIivGPjsLqbPYGv1OUbg2bq6JcLBgXivmiN+CI6C0LjlZEgYxaEw0ynyCbBTGkRRWSez5LiMsGHfPQynrw7MA6ZCkzfdVHCPT4HSdTCTc6g4kLvf7q2HRVeED07e8RFaNWrxJyOCE05L5PhKHpTilkJjrFVV19hluM95L1xnNEGWRpkJxjrFqwf7l2Y425+pTYwa2wrLdtULkGyLA2Wf7EHqGY2f9LZ3g32In1/do34MCDO/STUBpwIR+PqvATmqbVM8/otq1wmJD5yGmb0U9dp1CPZ3jdKjzlVJ8x7FLVwXhIKZJIh7RdOm7zsfmWvRvQkx0MyFtA4eoekYig+AmJEA+fCCqBQgdB1FHKRoElDUCRw3nyhhYamt6rDdqPxVPVHi87iRdg+OcUEtPNFrUxZDaJHU=
    dist: el/6
    local-dir: release
    package_glob: "*.rpm"
    skip_cleanup: true
    cleanup: false
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
  # Upload built files to github too.
  - provider: releases
    token:
      secure: CEeczHbmPCs54puNInkE7pCwPrR13Rl054PVtfElsXGD62DoJB6DAW2M9XEEVQPAaCZHj8K1mTRKA6h0W1xSyT0YYZkcVRzrpqkntGo1swfRtPj3nnUCJEqvABrMJWv7c/145LmcoXpalxMCHVOioQJO87hZf+iV+Keb2HwIUTChglVpjcDtTeSrQlKSn58jiYSaVQs4cgdrXhlBFxTwgeyVBTbbg7nU036GgCnQoU9gzWZysa6XGuO4MyoehRfNj5RHIbPITWqmUSbxUHV4G25+SrcP2MBEdZawvWKSrnSvKdYuczhmhv9rVIxNNOM+jRqIpLlaJjY+o1kWL9OBT/e9eqyfpvG7b1sYWyuzQPPNH02hV5NyXLobXtWDpuL8gCbtF/dLTjsom2PGC/g0/aeJ0GvwmSA/c2P8Oc2AajHX9kJ9JSq1R7Kg0JKHFZRwsdUb1sfoc2oyO9sh7YpMDx/6eVnkTekbhpXLdJyJd4pWj6FLllZP6GMVQehyOUANADKZQ1yWH+gPUbgvieEjd54ZqZO5/yPzOI0eIw9j48BCMRgjkY5wZkUJ+lLjN5qMS5Zrc4rSI4kU0UKrvvr9O32EczV6f54lRxp9TK89NuPkkcbCAWa9iVasdONOho5TRKRirp3W3jqWm2rSbKWjPg9axJ2ts53I8w8ybMdyFRE=
    overwrite: true
    skip_cleanup: true
    cleanup: false
    file_glob: true
    file: release/*
    on:
      tags: true
  # Upload homebrew formula file to a special repo.
  - provider: script
    script: bash scripts/formula-deploy.sh
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = osx"
